# -------------------------
# ------FUNCTIONS.PY-------
# This document gathers all the functions required to run the main.py file associated with our final project on image cleaning methods for Cherenkov-telescope images.
# Javier Riera Vidal and Helena Villares Santiago
# IPCV 2025-26 Universitat de Barcelona

#------GENERATION OF THE IMAGES------

# CLEAN IMAGE GENERATION
def clean_image(intensity, shape=(64, 64), sigma_x=50, sigma_y=10):
    """
    This function generates the elongated Guassian blob detected by a Cherenkov-telescope.

    input:
        intensity: the maximum intensity recorded at the centre of the bulb, in p.e.
        shape: tuple, the shape of the desired array, default =(64,64)
        sigma_x and sigma_y: desired withd and length of the bulb, default = 50, 10

    output:
        image: the clean image generated
    """
    import numpy as np

    # we start by creating an empty image
    clean_image = np.zeros(shape)

    # find the center within image bounds
    x0 = np.random.randint(int(shape[0] * 0.3), int(shape[0] * 0.7))
    y0 = np.random.randint(int(shape[1] * 0.3), int(shape[1] * 0.7))

    # create the meshgrid
    x, y = np.meshgrid(np.arange(shape[0]), np.arange(shape[1]), indexing='ij')

    #find the differences
    dx = x - x0
    dy = y - y0

    # find the random orientation in the sky
    angle = np.random.uniform(0, np.pi)

    dx_rot = dx * np.cos(angle) - dy * np.sin(angle)
    dy_rot = dx * np.sin(angle) + dy * np.cos(angle)

    # ellipse shape (elongated)
    value = np.exp(-(dx_rot**2 / sigma_x + dy_rot**2 / sigma_y))

    #we have to take into account the intensity
    clean_image += intensity * value 

    return clean_image

#NOISE GENERATION
def noise(sigma_noise=1.65, shape=(64,64)):
    """
    This function generates the random noise typical of the NSB (night sky background) recorded at Cherenkov Telescopes.

    input:
        sigma_noise: amplitude of the variations of noise, default=1.65pe
        shape: desired shape, has to be the the same used at clean_image to sum them, default=(64,64)

    output:
        noise
    """
    import numpy as np
    # we create the NSB, this is a random array with our desired size
    #our noise follows a gaussian with average 0 and standard desviation equal to sigma_noise

    noise = np.random.normal(loc=0, scale=sigma_noise, size = shape)

    return noise

#TIME GENERATION
def time(clean_image, time_arrival=15, time_desv=1, time_max=40):
    """
    This function adds the time of arrival of the maximum intensity for a given clean image
    input and the time of arrival of the different noise of the image

    input:
        clean_image: the clean image generated by clean_image()
        time_arrival: time of arrival of the ray, default=15 ns
        time_desv: desviation of time of arrival of theray, default=1 ns
        time_max: the maximum time that the camera of the telescope records, default=40 ns
    output: 
        time_array: array with the times of arrival of each pixel
    """
    import numpy as np

    #ens guardem la shape
    shape = np.shape(clean_image)

    # creem un array de zeros de la mida de la pròpia imatge
    time_array = np.zeros_like(clean_image)

    #separem el bulb del noise
    mask_bulb = clean_image > 0.1
    mask_noise = ~mask_bulb

    # build full time arrays and select by mask to avoid broadcast issues
    bulb_times = np.random.normal(loc=time_arrival, scale=time_desv, size=shape)
    noise_times = np.random.uniform(low=0.0, high=time_max, size=shape)
    time_array = np.where(mask_bulb, bulb_times, noise_times)

    return time_array


#------CLEANING METHODS IMPLEMENTED------

#TAIL-CUT CLEANING
def tailcut_cleaning(image, sigma_noise=1.65, high_thr=16, low_thr=9, NN=2):
    """
    This function reproduces the tail-cut cleaning method described at our reference paper and used widely at telescopes to clean images. It consists of a two thresholds method. The default values given for the variables are described at our reference paper and correspond to the 0916NN2 configuration.

    input:
        image: array to be cleaned
        sigma_noise: the standard desviation of noise, we suppose it known, although we could implement a function to compute it from our noisy image, default=1.65 pe
        high_thr: higher threshold used, default=16 pe
        low_thr: lower threshold used, default=9 pe
        NN: minimum number of neighbours considered to not deleting a pixel, default=2

    output:
        image_cleaned_tailcut: cleaned array
    """
    import numpy as np
    import scipy as sci

    # 1: we remove pixels with a signal below 3 sigma noise
    image_cleaned_tailcut = (image > 3*sigma_noise) * image

    # 2: we have to establish our variables:

    # miram un píxel en concret, aleshores sobreviu si:
    #   -si està per sobre de low_thr i té almenys NN veins per sobre de hight_thr
    #   -si està per sobre de high_thr i té almenys NN veins per sobre de low_thr

    #we create this kernel to look at the neighbours but not at the pixel itself
    kernel = np.array([ [1, 1, 1],
                        [1, 0, 1],
                        [1, 1, 1]])

    #miram quins píxels compleixen els thresholds
    high_mask = image_cleaned_tailcut > high_thr
    low_mask = image_cleaned_tailcut > low_thr

    #contam els veinats que cada pixel té a high i a low amb la convolució
    high_neighbours = sci.signal.convolve2d(high_mask, kernel, mode="same")
    low_neighbours = sci.signal.convolve2d(low_mask, kernel, mode="same")

    #cream les condicions finals:
    final_mask = (high_mask & (low_neighbours >= NN)) | (low_mask & (high_neighbours >= NN))

    # and we apply it to our image
    image_cleaned_tailcut = image_cleaned_tailcut * final_mask

    return image_cleaned_tailcut

#MORPHOLOGICAL CLEANING
def morphological_cleaning(image, sigma_noise=1.65):
    """
    This function implments the methods taught at LAB8 regarding morphology to clean images and reduce noise. 

    input:
        image: array to be cleaned
        sigma_noise: the standard desviation of noise, we suppose it known, although we could implement a function to compute it from our noisy image, default=1.65 pe
        high_thr: higher threshold used, default=16 pe
        low_thr: lower threshold used, default=9 pe
        NN: minimum number of neighbours considered to not deleting a pixel, default=2

    output:
        image_cleaned_morph: cleaned array 
    """
    import numpy as np
    import skimage as ski

    # first we have to binarize our image with some threshold
    # we will try, for instance, with the same global threshold 3 sigma_noise that we used before, as it lead to good results
    image_cleaned_morph = image.copy()
    binary_mask = image_cleaned_morph > 3 * sigma_noise

    #we will use this footprint 
    footprint = ski.morphology.square(3) 

    #we can use the opening and closing functions from skimage to do this
    mask_cleaned_morph = ski.morphology.opening(binary_mask, footprint=footprint)
    mask_cleaned_morph = ski.morphology.closing(mask_cleaned_morph, footprint=footprint)

    #and apply the mask to our image
    image_cleaned_morph = image_cleaned_morph * mask_cleaned_morph

    return image_cleaned_morph

#KMEANS CLEANING
def kmeans_cleaning(image, position_weight=0.2):
    """
    This function implments the methods taught at LAB7 regarding the use of K-Means. In this case, we use it to create a mask that clusters the image into two clusters: noise and ray. Typically kmeans, would be used just with the intensity, but the result is a global thresholding not much interesting. In this case, we have included the information of the position, scaled with the intensity and moduled by a paramter that gives the right weight to the position in front of the intensity

    input:
        image: array to be cleaned
        sigma_noise: the standard desviation of noise, we suppose it known, although we could implement a function to compute it from our noisy image, default=1.65 pe
        position_weight: controls the weight of the spatial distribution in front of the intensity recorded, default=0.2

    output:
        image_cleaned_kmeans: cleaned array 
    """
    import numpy as np
    from sklearn.cluster import KMeans
    from sklearn.preprocessing import StandardScaler

    #en primer lloc hem de preparar la informació de la imatge amb la forma adequada

    # hem de generar la informació espacial, tornant a generar la cuadricula de la imatge original
    size_x, size_y = image.shape
    x, y = np.meshgrid(np.arange(size_x), np.arange(size_y), indexing='ij')

    # les apilam en forma de [x, y, intensitat]
    img_info = np.column_stack((x.flatten(), y.flatten(), image.flatten()))

    #ara les normalitzam, per a que les tres característiques tenguin el mateix pes
    img_info = StandardScaler().fit_transform(img_info)

    #i assignem a les posicions el pes corresponent
    img_info[:,0] *= position_weight
    img_info[:,1] *= position_weight

    #domés volem separar bulb i noise
    n_clusters = 2 

    #ara ja podem aplicar kmeans, el random_state és per conveniència, el fet de fixar un valor domés assegura que SEMPRE surtin les labels en el mateix ordre
    kmeans = KMeans(n_clusters = n_clusters, random_state=20).fit(img_info)

    # extreim la intensitat de cada centroide
    intensidad_0 = kmeans.cluster_centers_[0, -1]
    intensidad_1 = kmeans.cluster_centers_[1, -1]

    # reconstruim l'array de labels
    clustered_image = kmeans.labels_.reshape(image.shape)

    # triem el cluster amb una major intensitat i l'establim com el de la informació, i el complementari e de soroll
    if intensidad_0 > intensidad_1:
        mask_cascada = (clustered_image == 0)
    else:
        mask_cascada = (clustered_image == 1)

    # netejam la imatge original
    image_cleaned_kmeans = image * mask_cascada

    return image_cleaned_kmeans

#DBSCAN CLEANING
def dbscan_cleaning(image, sigma_noise=1.65):
    """
    This function implements the DBSCAN (Density-Based Spatial Clustering of Applications with Noise) method to clean our noisy IACT images. The paper describes two possible algorithms, depending on the inclusion (TIME4D) or not (TIME3D) of the intensity.

    input:
        image: noisy image to be cleaned [:,:,0], includes the time channel [:,:,1]
        intensity_included: =False for time 3d (default) and =True for time4d
        
    output:
        image_cleaned_dbscan: the image cleaned, without time dependence
    """
    import numpy as np
    from sklearn.cluster import DBSCAN
    from sklearn.preprocessing import StandardScaler


    #CAS TIME3D
    #els millors parametres son:
    minpts = 4 #cerquem un petit nucli de 1 punt i 3 al seu voltant
    sscale = 2.0 #per poder connectar els voltants d'un punt
    tscale = 3.5 #per l'escala de temps en què es dispara el raig gamma
    nnoise = 1 #valors superiors són massa agressius
    
    #en primer lloc hem de preparar la informació de la imatge amb la forma adequada

    # hem de generar la informació espacial, tornant a generar la cuadricula de la imatge original
    size_x, size_y = image[:,:,0].shape
    x, y = np.meshgrid(np.arange(size_x), np.arange(size_y), indexing='ij')
    t = image[:,:,1]
    
    #realitzem un primer filtratge
    mask = image[:,:,0] > nnoise * sigma_noise

    x = x[mask]
    y = y[mask]
    t = t[mask]

    # les apilam en forma de [x, y, t]
    img_info = np.column_stack((x.flatten(), y.flatten(), t.flatten()))

    #ara les normalitzam, per a que les tres característiques tenguin el pes corresponent
    img_info[:,0] /= sscale
    img_info[:,1] /= sscale
    img_info[:,2] /= tscale

    #ara ja podem aplicar dbscan
    dbscan = DBSCAN(eps=1, min_samples=minpts).fit(img_info)
    
    #extreim les labels
    labels = dbscan.labels_

    #eliminam el noise
    labels_signal = labels[labels != -1]

    if labels_signal.size == 0:
        mask_final = np.zeros(image[:,:,0].shape, dtype=bool)
    else:
        #ens quedem amb el clúster més gran, el largest
        unique, counts = np.unique(labels_signal, return_counts=True)
        largest_cluster = unique[np.argmax(counts)]

        #reconstruim la màscara
        mask_final = np.zeros(image[:,:,0].shape, dtype=bool)
        mask_final[mask] = labels == largest_cluster

    #i finalment, aplicam la neteja
    image_cleaned_dbscan = image[:,:,0] * mask_final

    return image_cleaned_dbscan



#------METRICS IMPLEMENTED FOR COMPARISION------

def size_ret(clean_image, noise, image):
    """
    This function computes the metric that is used in the paper to compare the ground-truth with the result after filtering: the average remaining light retention and the average noise survival. 

    input: 
        clean_image: the image without noise, before cleaning
        noise: the noise added to the clean image
        image: the image after cleaning
    
    output:
        signal_retention: the signal retention calculated
        background_survival: the noise retention calculated
    """
    import numpy as np

    #we select where we had signal and noise originally
    mask_signal_truth = clean_image > 0.01
    mask_noise_truth = ~mask_signal_truth

    #and we select where we have signal now
    mask_cleaned = image != 0

    #first we look at the original signal and noise
    org_signal = np.sum(clean_image[mask_signal_truth])
    org_noise = np.sum(mask_noise_truth)

    #then we look at the signal and noise retained
    ret_signal = np.sum(clean_image[mask_cleaned & mask_signal_truth])
    ret_noise = np.sum(mask_noise_truth & mask_cleaned)

    #and we compute the signal and noise retention
    signal_retention = ret_signal/org_signal if org_signal > 0 else 0.0
    background_survival = ret_noise/org_noise if org_noise > 0 else 0.0

    return signal_retention, background_survival


